"""create audit_runs and reports tables

Revision ID: 8a89e59a6024
Revises: 
Create Date: 2026-09-14 00:23:21.970087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a89e59a6024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('overall_accuracy', sa.Float(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_run_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('validation_passed', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('audit_runs')
    # ### end Alembic commands ###
